# -*- coding: utf-8 -*-
"""Python Arrays 19/1/26 to 26/1/26

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BEjy5P9S1iJyIfH9YcBJFcUsXhRfopC
"""

# 1.You are given an array of integers arr[]. You have to reverse the given array.
#Note: Modify the array in place.
#Examples: Input: arr = [1, 4, 3, 2, 6, 5]
#Output: [5, 6, 2, 3, 4, 1]
#Explanation: The elements of the array are [1, 4, 3, 2, 6, 5]. After reversing the array, the first element goes to the last position, the second element goes to the
#second last position and so on. Hence, the answer is [5, 6, 2, 3, 4, 1].
#ANS
arr=[1,4,3,2,6,5]
print(arr[::-1])

#2.  Given an array arr[]. Your task is to find the minimum and maximum elements in the array.
# Examples: Input: arr[] = [1, 4, 3, 5, 8, 6] Output: [1, 8] Explanation: minimum and maximum elements of array are 1 and 8.
#ANS
brr=[1,4,3,5,8,6]
print(min(brr))
print(max(brr))

#3.Given an integer array arr[] and an integer k, your task is to find and return the kth smallest element in the given array.
#Note: The kth smallest element is determined based on the sorted order of the array.
#Examples : Input: arr[] = [10, 5, 4, 3, 48, 6, 2, 33, 53, 10], k = 4 Output: 5
#Explanation: 4th smallest element in the given array is 5.
crr=[10,5,4,3,48,6,2,33,53,10]
k=4
crr.sort()
print(crr[k-1])

#4. You are given two arrays a[] and b[], return the Union of both the arrays in any order.
#The Union of two arrays is a collection of all distinct elements present in either of the arrays. If an element appears more than once in one or both arrays, it should be
#included only once in the result. Note: Elements of a[] and b[] are not necessarily distinct.
#Note that, You can return the Union in any order but the driver code will print the result in sorted order only.
#Examples: Input: a[] = [1, 2, 3, 2, 1], b[] = [3, 2, 2, 3, 3, 2] Output: [1, 2, 3] Explanation: Union set of both the arrays will be 1, 2 and 3.
#Ans
a=[1,2,3,2,1]
b=[3,2,2,3,3,2]
c=a+b
print(set(c))

#5.